import { Router } from "express";
import Register from "../../controllers/admin/Register.js";
import AdminLogin from "../../controllers/admin/Login.js";
import PostDriver from "../../controllers/admin/PostDriver.js";
import ShowDriver from "../../controllers/admin/ShowDrivers.js";
import ShowTrips from "../../controllers/admin/ShowTrips.js";
import AssignTrips from "../../controllers/admin/PostAssigned.js";
import ShowAssigned from "../../controllers/admin/ShowAssigned.js";
import DeleteTrips from "../../controllers/admin/DeleteTrip.js";
import protectRoute from "../../middleware/protectRoute.js";
import ShowAdmins from "../../controllers/admin/ShowAdmins.js";
import ShowApplicants from "../../controllers/admin/ShowApplicants.js";
import DeleteApproved from "../../controllers/admin/DeleteApproved.js";
import ShowCompany from "../../controllers/admin/ShowCompany.js";
import ShowMessages from "../../controllers/admin/ShowMessages.js";
import ShowCompleted from "../../controllers/admin/ShowCompleted.js";
import SendPayment from "../../controllers/admin/SendPaymet.js";
import ShowPaymentSent from "../../controllers/admin/ShowPaymentSent.js";
import DeletePayments from "../../controllers/admin/DeletePayments.js";
import PostFinalPayment from "../../controllers/admin/FinalPayments.js";
import ShowPayments from "../../controllers/admin/ShowPayments.js";
import Showsight from "../../controllers/admin/Showsight.js";
import PostSightAssign from "../../controllers/admin/PostSightAssign.js";
import UnassignSight from "../../controllers/admin/UnassignSight.js";
import ShowAssignedSight from "../../controllers/admin/ShowAssingedSight.js";
import ShowReturnTrips from "../../controllers/admin/ShowReturnTrips.js";
import PostReturnTrips from "../../controllers/admin/PostReturnTrips.js";
import ShowAssignedReturns from "../../controllers/admin/ShowAssignedReturns.js";
import DeleteReturnAssigned from "../../controllers/admin/DeleteReturnAssigned.js";
import ShowCustomerList from "../../controllers/admin/CustomerList.js";

const admin = Router();

admin.post("/register", protectRoute, Register);
admin.post("/login", AdminLogin);
admin.post("/post-driver", protectRoute, PostDriver);
admin.get("/drivers", protectRoute, ShowDriver);
admin.get("/trips", protectRoute, ShowTrips);
admin.post("/assign", protectRoute, AssignTrips);
admin.get("/assignedTrips", protectRoute, ShowAssigned);
admin.delete("/unassign/:id", protectRoute, DeleteTrips);
admin.get("/admins", protectRoute, ShowAdmins);
admin.get("/applicants", protectRoute, ShowApplicants);
admin.delete("/removeapplicant/:id", protectRoute, DeleteApproved);
admin.get("/showcompanies", protectRoute, ShowCompany);
admin.get("/showmessages", protectRoute, ShowMessages);
admin.get("/completed", protectRoute, ShowCompleted);
admin.post("/sendpayment", protectRoute, SendPayment);
admin.get("/showsent", protectRoute, ShowPaymentSent);
admin.delete("/deletepay/:driverId", protectRoute, DeletePayments);
admin.post("/postfinal", protectRoute, PostFinalPayment);
admin.get("/showpayments", protectRoute, ShowPayments);
admin.get("/sightseeing", protectRoute, Showsight);
admin.post("/postsight", protectRoute, PostSightAssign);
admin.delete("/unassignsight/:id", protectRoute, UnassignSight);
admin.get("/showassigned", protectRoute, ShowAssignedSight);
admin.get("/returntrips", protectRoute, ShowReturnTrips);
admin.post("/postreturns", protectRoute, PostReturnTrips);
admin.get("/showassignedreturns", protectRoute, ShowAssignedReturns);
admin.delete("/deleteassigned/:id", protectRoute, DeleteReturnAssigned);
admin.get("/allcustomers", protectRoute, ShowCustomerList);

export default admin;
